# Generated by Django 4.2.11 on 2024-04-26 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('e40bce42-8c9b-43a6-a2a7-e32c60b989c2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
