# Generated by Django 4.2.11 on 2024-04-26 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('0575a21e-02f4-41b9-9215-a4b78a5d6c5d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
