# Generated by Django 4.2.11 on 2024-04-26 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('b6eb09d0-03c1-415e-959b-97a4b2eff101'), editable=False, primary_key=True, serialize=False),
        ),
    ]
