# Generated by Django 4.2.11 on 2024-04-26 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('678d120a-1f38-4ed0-a5eb-4022fb4d5abd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
