<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-04-27 08:45
=======
# Generated by Django 4.2.11 on 2024-04-26 13:52
>>>>>>> 36af7f61ffdcae1f28ee2c3a6cede69a7c8f7e72

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
<<<<<<< HEAD
            field=models.UUIDField(default=uuid.UUID('12a92176-0e00-4dd0-97c0-a3128de63ee7'), editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default=uuid.UUID('678d120a-1f38-4ed0-a5eb-4022fb4d5abd'), editable=False, primary_key=True, serialize=False),
>>>>>>> 36af7f61ffdcae1f28ee2c3a6cede69a7c8f7e72
        ),
    ]
