# Generated by Django 4.2.11 on 2024-04-27 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('12a92176-0e00-4dd0-97c0-a3128de63ee7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
