# Generated by Django 4.2.11 on 2024-04-26 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('b5cf3276-41be-4314-9ca1-a0df8c2d32c8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
