# Generated by Django 4.2.11 on 2024-04-29 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('87bee9b5-e3a6-4d1a-b3b1-ec1bb9b6aaf7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
