# Generated by Django 4.2.11 on 2024-05-04 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('b5df0e34-d3a4-4d13-95ce-c9c3f5884b33'), editable=False, primary_key=True, serialize=False),
        ),
    ]
