# Generated by Django 4.2.11 on 2024-05-05 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('72ab062b-f10a-4184-bde2-e475a1983f7f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
