# Generated by Django 4.2.11 on 2024-05-08 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('78246a4d-ddf6-4c93-b272-996c0827ba4c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
