# Generated by Django 4.2.11 on 2024-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(default='Tehran', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
